discord:
  command_prefix: '//'
  bot_api_key: ''
  admin_command_channel_id: ''
  admin_shouts_channel_id: ''
  shouts_public_notification_channel_id: ''
  in_limbo_role_id: 
  retired_without_honors_role_id: 
  guild_id: 
  admin_user_ids:
    - ''
    - ''
    
spectator_accounts:
  display_action_bar: true
  force_spectator_gamemode_on_join: true
  disable_spectator_accounts: false
  non_members_are_spectator: false
  prevent_chat: true

limbo:
  sent_to_to_limbo_message: 'Hey there {MC_USERNAME},\nYou have been automatically been given the Limbo role.\nSee the following link for what this means for your future on The Introverts Cove:: https:://introvertscove.net/limbo-faq'
  time_from_last_logout_until:
    nag_message: -1
    sent_to_limbo: 691200
    auto_retire_danger_message: 1728000
    auto_retire: 1900800 
  
rest_api_server:
  allowed_api_keys:
    - ''    