name: IntrovertsCoveSurvivalServer
version: 1.0-INDEV
main: net.introvertscove.survivalserver.plugin.SurvivalServerPluginMain
authors: [JustBru00, Justin Brubaker]
api-version: 1.16

commands:
  member:
    description: This command allows adding and removing members to the server.
  spectatoraccounts:
    description: This command allows adding and removing spectator accounts. It also allows setting different options involved with spoectator accounts.
  limbo:
    description: This command allows adding/viewing limbo excemptions.
  whois:
    description: This command shows a lot of player information based off of the member MCusername.       
  sessionhistory:
    description: This command displays the given players session history.      